#!/bin/bash

set -x

RF=3
IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    IP=$(grep $(hostname) /etc/hosts | grep -v ext | awk '{print $1}')
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    IP=localhost
    RF=1
fi

cqlsh "$IP" -e "
CREATE KEYSPACE if not exists finance WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '"$RF"'}  AND durable_writes = true;

CREATE TABLE finance.correlations (
    symbol_pair text,
    epoch_seconds bigint,
    corr_10 double,
    corr_100 double,
    corr_50 double,
    PRIMARY KEY (symbol_pair, epoch_seconds)
) WITH CLUSTERING ORDER BY (epoch_seconds DESC);

CREATE TABLE finance.daily_stock_prices (
    symbol text,
    epoch_seconds bigint,
    price decimal,
    PRIMARY KEY (symbol, epoch_seconds)
) WITH CLUSTERING ORDER BY (epoch_seconds DESC);

CREATE TABLE finance.financial_instruments (instrument text, stock_symbols text, primary key (instrument)  );

insert into finance.financial_instruments (instrument, stock_symbols ) values ('unusual_correlations',
'GM|PIO,C|SUP,DIS|XLI,COKE|ELP,VZ|CPK,AMZN|WCN,F|WOOD,BA|MDT,YUM|WES,MCD|SO,MSFT|ABG,NKE|TGI,ANF|SFLY,VIA|PBJ');"

